const r = new Router(
    {
        alerts: new Layout(new Page('menu.html'), new Page('alerts.html')),
        chips: new Layout(new Page('menu.html'), new Page('chips.html')),
        check: new Layout(new Page('menu.html'), new Page('check.html')),
        lists: new Layout(new Page('menu.html'), new Page('lists.html')),
        card: new Layout(new Page('menu.html'), new Page('card.html')),
        fonts: new Layout(new Page('menu.html'), new Page('fonts.html')),
        buttons: new Layout(new Page('menu.html'), new Page('buttons.html')),
        tables: new Layout(new Page('menu.html'), new Page('tables.html')),
        snackBar: new Layout(new Page('menu.html'), new Page('snackBar.html')),
        banner: new Layout(new Page('menu.html'), new Page('banner.html')),
        forms: new Layout(new Page('menu.html'), new Page('forms.html')),
        image: new Layout(new Page('menu.html'), new Page('image.html')),
        progressBar: new Layout(new Page('menu.html'), new Page('progressBar.html')),
        datePicker: new Layout(new Page('menu.html'), new Page('datePicker.html')),
        dropDown: new Layout(new Page('menu.html'), new Page('dropDown.html')),
        breadcrumb: new Layout(new Page('menu.html'), new Page('breadcrumb.html')),
        tooltip: new Layout(new Page('menu.html'), new Page('tooltip.html')),
        modal: new Layout(new Page('menu.html'), new Page('modal.html')),
        panel: new Layout(new Page('menu.html'), new Page('panel.html')),
        tabs: new Layout(new Page('menu.html'), new Page('tabs.html')),
        actionItem: new Layout(new Page('menu.html'), new Page('actionItem.html')),
        calendar: new Layout(new Page('menu.html'), new Page('calendar.html')),
        dividers: new Layout(new Page('menu.html'), new Page('dividers.html')),
        animations: new Layout(new Page('menu.html'), new Page('animations.html')),
        steps: new Layout(new Page('menu.html'), new Page('steps.html')),
        charts: new Layout(new Page('menu.html'), new Page('charts.html')),
        carousel: new Layout(new Page('menu.html'), new Page('carousel.html')),
        gallery: new Layout(new Page('menu.html'), new Page('gallery.html')),
        icons: new Layout(new Page('menu.html'), new Page('icons.html')),
        chat: new Layout(new Page('menu.html'), new Page('chat.html')),
        tree: new Layout(new Page('menu.html'), new Page('tree.html')),
        testing: new Layout(new Page('menu.html'), new Page('testing.html')),
        filters: new Layout(new Page('menu.html'), new Page('filters.html')),
        colors: new Layout(new Page('menu.html'), new Page('colors.html')),
        '#default': new Page('menu.html'),
    },
    document.querySelector('main')
);
